### ISSUE TITLE
script launch_buchwald_hartwig_training.py hangs

### ISSUE THREAD

**Issue by PrzemekPobrotyn** [rxn4chemistry/rxnfp#10] opened 2021-05-31 11:31 UTC
Hi,

I've been trying to reproduce results from your YieldBERT paper and have run into some issues.

I've created the conda env following the instructions from the readme and tried running `python  launch_buchwald_hartwig_training.py pretrained`. I got a `xlrd.biffh.XLRDError: Excel xlsx file; not supported` when the scripts tried reading the data, but downgrading xlrd to version 1.2.0 fixed that. 

However, when running the above scripts, the training hangs after the second epoch. Output of my terminal is 
![Screenshot 2021-05-31 at 1 14 53 pm](https://user-images.githubusercontent.com/29800294/120185684-d1ccec80-c212-11eb-9b42-baaa70b2d244.png)
and it stays like that indefinitely.

Wandb system logs show GPU usage of about 88%, around 4% non-swap memory in use, cpu utilisation of around 20% - all seemed normal to me, perhaps expect process CPU threads graph which looks like that:
![image](https://user-images.githubusercontent.com/29800294/120186193-764f2e80-c213-11eb-8e4e-c16b0455413d.png)

I'm running the script on a machine with Ubuntu 16.04, a single K80 GPU with CUDA version 11.0 and conda version 4.10.1.

The script hangs similarly after 2nd epoch when running `python repro_neurips_buchwald_hartwig_experiments.py  randomsplit-canonical`, i.e. both scripts hang at global step 300.

Since it's not throwing any errors I'm a bit stuck on what to do with it.

**Comment by pschwllr** [comment] 2021-05-31 15:47
That's weird. Some people have reported similar problems with SimpleTransformers models (that are used with Yield-BERT): https://github.com/ThilinaRajapakse/simpletransformers/issues/1030

For me it works with Ubuntu 18.04, a single RTX 2070 GPU and CUDA 11.0. 

Can you try turning off multiprocessing? 

("use_multiprocessing": False, in the model_args -> https://github.com/rxn4chemistry/rxn_yields/blob/47e4e830ca071ba3053da578da5270bfc5fd1a52/training_scripts/repro_neurips_buchwald_hartwig_experiments.py#L182)

**Comment by PrzemekPobrotyn** [comment] 2021-05-31 16:23
Setting multiprocessing to False in the `launch_buchwald_hartwig_training.py` script did not help. Looking at the issue you linked - I'll see if wandb is not causing any problems with multiprocessing and report back here.

**Comment by PrzemekPobrotyn** [comment] 2021-06-01 11:38
Disabling wandb didn't help, however, I run the script on a different setup (a personal Mac) and instead of the script hanging got the following traceback:

![image](https://user-images.githubusercontent.com/29800294/120316846-2a1cf080-c2de-11eb-9dfe-f01874538d85.png)

stackoverflow users suggest increasing the limit /etc/security/limits.conf  which I'm about to try but it looks like an issue in simpletransformers with the trainig script not closing files properly?

**Comment by pschwllr** [comment] 2021-06-04 07:10
Not sure if this could help you. https://github.com/ThilinaRajapakse/simpletransformers/issues/1053

What `torch` version have you installed?

**Comment by pschwllr** [comment] 2021-08-12 09:23
The issue is related to https://github.com/rxn4chemistry/rxn_yields/ and might have been fixed by the recent `rxnfp` update. Closing for now.

**Closed by pschwllr** 2021-08-12 09:23 UTC

**Comment by A-Thakkar** [comment] 2021-08-30 12:42
You can also try setting the following variable:

os.environ["TOKENIZERS_PARALLELISM"] = "false"

Even though multi-processing is False the hugging face tokenisers may use parallelism by default. You can set this to turn off using the above environment variable.
